services:
  Router:
    class: 'Router'
    public: true

  Beauty\Request:
    class: 'Beauty\Request'
    factory: 'Beauty\Request::instance'

  Admin\Router:
    autowire: true
    public: true

  Session\SessionServiceClient:
    class: 'Session\SessionServiceClient'
    public: true
    arguments:
      $hostname: '%service.session.hostname%'
      $opts: '%service.session.opts%'
