services:
  Router:
    class: 'Router'
    public: true

  Beauty\Request:
    class: 'Beauty\Request'
    factory: 'Beauty\Request::instance'

  Admin\Router:
    autowire: true
    public: true

  Session\SessionServiceClient:
    class: 'Session\SessionServiceClient'
    public: true
    arguments:
      $hostname: '%service.session.hostname%'
      $opts: '%service.session.opts%'
      $channel: '@Grpc\Channel'

  Grpc\Channel:
    class: 'Grpc\Channel'
    arguments:
      $target: '%service.session.hostname%'
      $args: '%service.session.opts%'

  Session:
    class: 'Session'
    autowire: true

  NetworkTransport\Http\Transport:
    autowire: true

  Alexander1000\Clients\Users\Client:
    autowire: true
    arguments:
      $requestBuilder:
        !service
        class: 'NetworkTransport\Http\Request\Builder'
        arguments:
          $host: '%service.users.host%'
          $headers: '%service.users.headers%'
          $options: '%service.users.options%'

  Alexander1000\Clients\Auth\Client:
    autowire: true
    arguments:
      $requestBuilder:
        !service
        class: 'NetworkTransport\Http\Request\Builder'
        arguments:
          $host: '%service.auth.host%'
          $headers: '%service.auth.headers%'
          $options: '%service.auth.options%'
