version: "3.8"
services:
  php:
    image: dankovtsev.pro:5000/utils/php
    volumes:
      - type: bind
        source: .
        target: /home/www-data/dankovtsev.pro/release
  nginx:
    image: dankovtsev.pro:5000/utils/nginx
    ports:
      - "8080:80"
    links:
      - "php:backend"
    volumes:
      - type: bind
        source: ./templates/errors
        target: /home/www-data/dankovtsev.pro/release/templates/errors
