version: "3.8"
services:
  backend:
    image: dankovtsev.pro:5000/utils/php
    volumes:
      - type: bind
        source: .
        target: /home/www-data/dankovtsev.pro/release
    networks:
      - backend
  nginx:
    image: dankovtsev.pro:5000/utils/nginx
    ports:
      - "8080:80"
    networks:
      - backend
    volumes:
      - type: bind
        source: ./templates/errors
        target: /home/www-data/dankovtsev.pro/release/templates/errors
      - type: bind
        source: ./www/css
        target: /home/www-data/dankovtsev.pro/release/www/css
    extra_hosts:
      core.dankovtsev.pro: "81.163.28.190" # @todo: hard code, fix with dns resolving
networks:
  backend:
    driver: bridge
