parameters:

  service.session.hostname: core.dankovtsev.pro:8889
  service.session.opts: []

  service.users.host: http://core.dankovtsev.pro:8888/service-users

  service.auth.host: http://core.dankovtsev.pro:8888/service-auth
