main:
  uri: /
  controller: Controller\Site
  action: index

admin_area:
  uri: /admin
  route: true
  class: Admin\Router

auth_login:
  uri: /login
  controller: Auth\Controller\Login
  action: login
